option(USE_ADDRESS_SANITIZER "Use sanitizers" OFF)
option(USE_LIBCPP "Use libc++ when compiling with clang" OFF)
option(STRICT_COMPILATION "Enable -Werror strict compilation" ON)
option(PRECOMPILED_HEADERS "Use precompiled headers" ON)
option(USE_ADDRESS_SANITIZER "Use address sanitizers" OFF)
option(USE_THREAD_SANITIZER "Use thread sanitizers" OFF)
option(CREATE_STATIC_LIBRARY "Create static version of library " OFF)

message(STATUS "CC " ${CMAKE_C_COMPILER})
message(STATUS "CXX " ${CMAKE_CXX_COMPILER})
message(STATUS "Build type: " ${CMAKE_BUILD_TYPE})
message(STATUS "Use libcpp? " ${USE_LIBCPP})
message(STATUS "Strict compilation? " ${STRICT_COMPILATION})
message(STATUS "Precompiled headers? " ${PRECOMPILED_HEADERS})
message(STATUS "Address sanitizer? " ${USE_ADDRESS_SANITIZER})
message(STATUS "Thread sanitizer? " ${USE_THREAD_SANITIZER})
message(STATUS "Static version? " ${CREATE_STATIC_LIBRARY})
